In [ ]:
!pip install git+https://github.com/ultralytics/ultralytics.git@main

# Train

In [1]:
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

In [2]:
model

YOLO(
  (model): DetectionModel(
    (model): Sequential(
      (0): Conv(
        (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): C2f(
        (cv1): Conv(
          (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(48, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_s

In [ ]:
result = model.train(data='detector.yaml', epochs=4, imgsz=640 )

In [ ]:
model.export(format =  'torchscript')

# Inference

In [68]:
from ultralytics import YOLO

#model = YOLO(".\\runs\\detect\\freeze_50epoch\\weights\\best.pt")
model = YOLO('..\\models\\fiber_only.pt')
img_path = '.\\sample7.jpg'
results = model.predict(img_path, conf = 0.2, iou = 0.7)
results[0].show()


image 1/1 d:\Deep learning\sample7.jpg: 640x640 2 Cottons, 4 Polyesters, 1 Polyurethane, 208.2ms
Speed: 4.0ms preprocess, 208.2ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)


In [7]:
results = model.predict(img_path, conf = 0.01, iou = 0.7)


image 1/1 d:\Deep learning\sample6.jpg: 640x640 12 persons, 1 backpack, 23 umbrellas, 6 handbags, 3 ties, 4 kites, 1 wine glass, 1 cup, 1 knife, 4 bananas, 4 cakes, 8 chairs, 3 beds, 1 dining table, 3 books, 1 clock, 1 teddy bear, 215.6ms
Speed: 8.0ms preprocess, 215.6ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)


In [3]:
str(results[0].boxes.data)

'tensor([[3.9712e+02, 2.5439e+02, 5.2375e+02, 3.9467e+02, 4.5489e-01, 0.0000e+00],\n        [2.9785e+02, 5.5100e+02, 4.6310e+02, 6.8978e+02, 4.1902e-01, 0.0000e+00],\n        [8.0542e+01, 3.3324e+01, 1.7543e+02, 1.4294e+02, 3.6300e-01, 0.0000e+00],\n        [6.3341e+02, 5.4578e+02, 6.8964e+02, 6.8963e+02, 3.4791e-01, 0.0000e+00],\n        [2.9086e+02, 4.0108e+02, 4.4099e+02, 5.4324e+02, 3.0630e-01, 2.5000e+01],\n        [5.7883e+02, 3.9241e+02, 6.8979e+02, 5.3876e+02, 2.8946e-01, 2.5000e+01],\n        [7.4683e-02, 5.6403e+02, 2.5613e+01, 6.8852e+02, 2.5250e-01, 7.4000e+01],\n        [1.2512e-01, 3.9823e+02, 5.3653e+01, 5.3321e+02, 2.0458e-01, 5.5000e+01],\n        [1.2465e+02, 1.3721e+02, 2.3201e+02, 2.4894e+02, 1.6341e-01, 0.0000e+00],\n        [1.2103e-01, 4.7729e+01, 8.3249e+01, 1.3595e+02, 1.5648e-01, 2.5000e+01],\n        [1.8486e+02, 4.8223e+01, 2.9910e+02, 1.3408e+02, 1.3858e-01, 2.5000e+01],\n        [1.2433e+02, 1.3701e+02, 2.3256e+02, 2.4847e+02, 1.3801e-01, 2.4000e+01],\n   

In [5]:
results[0].show()

# Tracking Test

In [ ]:
from ultralytics import YOLO
import cv2
from matplotlib import pyplot as plt


model = YOLO("..\\models\\fiber_only.pt")
#model = YOLO("yolov8n.pt")

img = cv2.imread(".\\sample3.jpg")
results = model.track(img, conf=0.2, persist=True, tracker = ".\\config\\tracker.yaml")
annotated_frame = results[0].plot()
plt.imshow(annotated_frame)

In [ ]:
print(results[0].boxes[0].id)
print(results[0].boxes[1].id)

# DETECTION + NMS + TRACKING
boxes -> new_boxes + new_boxes_cls

In [97]:
# detection
from ultralytics import YOLO

model = YOLO("..\\models\\fiber_only.pt")

img_file = ".\\sample6.jpg"
results = model.predict(img_file, conf = 0.01, iou = 0.7)
results[0].show()


image 1/1 d:\Deep learning\sample6.jpg: 640x640 4 cottons, 2 wools, 2 viscos rayons, 4 polyesters, 1 nylon, 1 polyurethane, 2 synthetic fiber otherss, 235.8ms
Speed: 11.2ms preprocess, 235.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)


In [98]:
results[0].boxes

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([ 8.,  8., 11.,  0.,  8.,  0.,  4.,  9.,  6., 11.,  4.,  8.,  0.,  6., 10.,  0.])
conf: tensor([0.3348, 0.3310, 0.2932, 0.2398, 0.2266, 0.1631, 0.1005, 0.0859, 0.0784, 0.0698, 0.0672, 0.0638, 0.0631, 0.0568, 0.0467, 0.0169])
data: tensor([[2.1573e+01, 5.4529e+02, 1.5682e+02, 6.8999e+02, 3.3480e-01, 8.0000e+00],
        [6.0419e+01, 5.4566e+02, 6.7498e+02, 6.9000e+02, 3.3104e-01, 8.0000e+00],
        [2.8460e+01, 5.4943e+02, 6.8760e+02, 6.9000e+02, 2.9316e-01, 1.1000e+01],
        [9.1173e+01, 5.4581e+02, 6.8267e+02, 6.9000e+02, 2.3983e-01, 0.0000e+00],
        [1.5145e+02, 6.2016e+02, 2.9770e+02, 6.8990e+02, 2.2659e-01, 8.0000e+00],
        [2.3994e+01, 5.4518e+02, 1.5702e+02, 6.8996e+02, 1.6307e-01, 0.0000e+00],
        [5.4352e+01, 5.5377e+02, 6.8788e+02, 6.9000e+02, 1.0051e-01, 4.0000e+00],
        [2.9543e+01, 5.4788e+02, 6.8595e+02, 6.9000e+02, 8.5910e-02, 9.0000e+00],
        [2.3559e+01, 5.4544e+02, 1.5650e+02

In [99]:
from ultralytics.engine.results import Boxes
data = results[0].boxes.data.clone()
orig_shape = results[0].boxes.orig_shape

data
# box score class

tensor([[2.1573e+01, 5.4529e+02, 1.5682e+02, 6.8999e+02, 3.3480e-01, 8.0000e+00],
        [6.0419e+01, 5.4566e+02, 6.7498e+02, 6.9000e+02, 3.3104e-01, 8.0000e+00],
        [2.8460e+01, 5.4943e+02, 6.8760e+02, 6.9000e+02, 2.9316e-01, 1.1000e+01],
        [9.1173e+01, 5.4581e+02, 6.8267e+02, 6.9000e+02, 2.3983e-01, 0.0000e+00],
        [1.5145e+02, 6.2016e+02, 2.9770e+02, 6.8990e+02, 2.2659e-01, 8.0000e+00],
        [2.3994e+01, 5.4518e+02, 1.5702e+02, 6.8996e+02, 1.6307e-01, 0.0000e+00],
        [5.4352e+01, 5.5377e+02, 6.8788e+02, 6.9000e+02, 1.0051e-01, 4.0000e+00],
        [2.9543e+01, 5.4788e+02, 6.8595e+02, 6.9000e+02, 8.5910e-02, 9.0000e+00],
        [2.3559e+01, 5.4544e+02, 1.5650e+02, 6.9000e+02, 7.8436e-02, 6.0000e+00],
        [1.8824e+01, 5.4573e+02, 1.5698e+02, 6.9000e+02, 6.9789e-02, 1.1000e+01],
        [2.0250e+01, 5.4578e+02, 1.5661e+02, 6.9000e+02, 6.7210e-02, 4.0000e+00],
        [2.9189e+02, 4.0068e+02, 4.4302e+02, 5.4019e+02, 6.3760e-02, 8.0000e+00],
        [1.5261e

In [100]:
# data sort by confidence score
data = results[0].boxes.data.clone()
indices = data[:, 4].sort(descending=True).indices
data = data[indices]
data

tensor([[2.1573e+01, 5.4529e+02, 1.5682e+02, 6.8999e+02, 3.3480e-01, 8.0000e+00],
        [6.0419e+01, 5.4566e+02, 6.7498e+02, 6.9000e+02, 3.3104e-01, 8.0000e+00],
        [2.8460e+01, 5.4943e+02, 6.8760e+02, 6.9000e+02, 2.9316e-01, 1.1000e+01],
        [9.1173e+01, 5.4581e+02, 6.8267e+02, 6.9000e+02, 2.3983e-01, 0.0000e+00],
        [1.5145e+02, 6.2016e+02, 2.9770e+02, 6.8990e+02, 2.2659e-01, 8.0000e+00],
        [2.3994e+01, 5.4518e+02, 1.5702e+02, 6.8996e+02, 1.6307e-01, 0.0000e+00],
        [5.4352e+01, 5.5377e+02, 6.8788e+02, 6.9000e+02, 1.0051e-01, 4.0000e+00],
        [2.9543e+01, 5.4788e+02, 6.8595e+02, 6.9000e+02, 8.5910e-02, 9.0000e+00],
        [2.3559e+01, 5.4544e+02, 1.5650e+02, 6.9000e+02, 7.8436e-02, 6.0000e+00],
        [1.8824e+01, 5.4573e+02, 1.5698e+02, 6.9000e+02, 6.9789e-02, 1.1000e+01],
        [2.0250e+01, 5.4578e+02, 1.5661e+02, 6.9000e+02, 6.7210e-02, 4.0000e+00],
        [2.9189e+02, 4.0068e+02, 4.4302e+02, 5.4019e+02, 6.3760e-02, 8.0000e+00],
        [1.5261e

In [71]:
# iou 계산
# box = [x_min, y_min, x_max, y_max]

def get_iou(box1, box2):
    def _is_box_intersect(box1, box2):
        if box1[2] <= box2[0] or box2[2] <= box1[0]:
            return False
        if box1[3] <= box2[1] or box2[3] <= box1[1]:
            return False
        return True
    def _get_area(box):
        return (box[2] - box[0]) * (box[3] - box[1])
    def _get_intersection_area(box1, box2):
        w = min(box1[2], box2[2]) - max(box1[0], box2[0])
        h = min(box1[3], box2[3]) - max(box1[1], box2[1])
        return w * h
    def _get_union_area(box1, box2):
        return _get_area(box1) + _get_area(box2) - _get_intersection_area(box1, box2)
    
    if not _is_box_intersect(box1, box2):
        return 0
    
    i_area = _get_intersection_area(box1, box2)
    u_area = _get_union_area(box1, box2)
    iou = i_area / u_area
    
    return iou

In [101]:
# NMS - fiber_only
new_boxes = []
iou_thresh = 0.5

for cur in data:
    is_new = True
    for box in new_boxes:
        iou = get_iou(cur, box)
        if iou >= iou_thresh:
            is_new = False
            break
    if is_new:
        new_boxes.append(cur)      

In [48]:
# NMS - 96 classes
new_boxes = []
new_boxes_cls = []
iou_thresh = 0.5

for cur in data:
    is_new = True
    for box, box_cls in zip(new_boxes, new_boxes_cls):
        iou = get_iou(cur, box)
        if iou >= iou_thresh:
            is_new = False
            fiber = int(cur[5]//8)
            box_cls[0].add(fiber)
            break
    if is_new:
        new_boxes.append(cur)
        washing = int(cur[5]%8)
        fiber = int(cur[5]//8)
        new_boxes_cls.append([set([fiber]), washing])        

In [102]:
# NMS 결과
new_boxes

[tensor([2.1573e+01, 5.4529e+02, 1.5682e+02, 6.8999e+02, 3.3480e-01, 8.0000e+00]),
 tensor([6.0419e+01, 5.4566e+02, 6.7498e+02, 6.9000e+02, 3.3104e-01, 8.0000e+00]),
 tensor([1.5145e+02, 6.2016e+02, 2.9770e+02, 6.8990e+02, 2.2659e-01, 8.0000e+00]),
 tensor([2.9189e+02, 4.0068e+02, 4.4302e+02, 5.4019e+02, 6.3760e-02, 8.0000e+00]),
 tensor([6.3289e+02, 5.6145e+02, 6.9000e+02, 6.9000e+02, 1.6884e-02, 0.0000e+00])]

In [103]:
# NMS 처리 후 box 생성
import torch
new_boxes = torch.stack(new_boxes)
new_boxes = Boxes(new_boxes, orig_shape)

In [145]:
# tracking
from ultralytics.trackers.bot_sort import BOTSORT
from argparse import Namespace


args = {
    'track_high_thresh' : 0.01, # threshold for the first association
    'track_low_thresh' : 0.001, # threshold for the second association
    'new_track_thresh' : 0.001, # threshold for init new track if the detection does not match any tracks
    'track_buffer' : 30, # buffer to calculate the time when to remove tracks
    'match_thresh' : 0.8,

    'gmc_method' : 'sparseOptFlow',
    'proximity_thresh' : 0.5,
    'appearance_thresh' : 0.25,
    'with_reid' : False

}
tracking_model = BOTSORT(Namespace(**args))

In [146]:
track_result = tracking_model.update(new_boxes)

In [140]:
tracking_model.lost_stracks

[OT_4_(1-1), OT_5_(1-1), OT_6_(2-3), OT_7_(2-3), OT_8_(2-3)]

In [147]:
track_result

array([[     21.573,      545.29,      156.82,      689.99,           1,      0.3348,           8,           0],
       [     60.419,      545.66,      674.98,         690,           2,     0.33104,           8,           1],
       [     151.45,      620.16,       297.7,       689.9,           3,     0.22659,           8,           2],
       [     291.89,      400.68,      443.02,      540.19,           4,     0.06376,           8,           3],
       [     632.89,      561.45,         690,         690,           5,    0.016884,           0,           4]], dtype=float32)

In [ ]:
# visualization
fiber_class = {
    0 :"Cotton",
    1 : "Hemp",
    2 : "cellulose fiber Others",
    3 : "Silk",
    4 : "Wool",
    5 : "protein fiber Others",
    6 : "Viscos rayon",
    7 : "regenerated fiber Others",
    8 : "Polyester",
    9 : "Nylon",
    10 : "Polyurethane",
    11 : "synthetic fiber Others"
}

washing_method_class = {
    0 : "hand washing30",
    1 : "washing30",
    2 : "washing40", #     "washing40_1" : 2,
    3 : "washing60",
    4 : "washing95",

    5 : "dryclean",
    6 : "dryclean : laundry",
    7 : "dryclean : petroleum solvent only"
}

import cv2
import matplotlib.pyplot as plt

img = cv2.imread(img_file)
for result in track_result:
    cv2.rectangle(img, (int(result[0]), int(result[1])), (int(result[2]), int(result[3])), (255,0,0))
    id_and_class = "id " + str(int(result[4])) + " / "
    for fiber in new_boxes_cls[int(result[7])][0]:
         id_and_class += fiber_class[fiber] + ", "
    id_and_class += washing_method_class[new_boxes_cls[int(result[7])][1]]
    cv2.putText(img, id_and_class,(int(result[0]), int(result[1])), cv2.FONT_ITALIC, 0.5, (255, 0, 0))

img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)